name: texlo

services:
  postgres:
    image: postgres:16
    container_name: texlo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ../docker/texlo/postgres/:/var/lib/postgresql/data
    ports:
      - 54325:5432
    restart: unless-stopped
    networks:
      - texlo

  valkey:
    image: valkey/valkey:latest
    container_name: texlo-valkey
    volumes:
      - ../docker/texlo/valkey:/data
    ports:
      - 6370:6379
    restart: unless-stopped
    networks:
      - texlo

  mongo:
    image: mongo:4.4.18
    container_name: texlo-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: texlo
      MONGO_INITDB_ROOT_PASSWORD: texlo
      MONGO_INITDB_DATABASE: texlo
    volumes:
      - ../.docker/texlo/mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - texlo

networks:
  texlo:
    driver: bridge
